version: "3.9"

services:
    laravelapp:
        container_name: laravelapp
        build: .
        ports:
            - "8001:8001"
        env_file:
            -   .env
        depends_on:
            - db

    db:
        container_name: db
        image: postgres:12
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: {}
